Repository source-academy/js-slang, pull requests merged in 2024-02, with the labels that each got.

#1518 CSE Machine: Fix array expression unpack order
  src/ec-evaluator/__tests__/__snapshots__/ec-evaluator-errors.ts.snap
  src/ec-evaluator/__tests__/__snapshots__/ec-evaluator.ts.snap
  src/ec-evaluator/__tests__/ec-evaluator.ts
  src/ec-evaluator/interpreter.ts
Labels: Bug

#1514 CSE Machine: Rename to CS1101S terms
  src/__tests__/inspect.ts
  src/createContext.ts
  src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap
  src/cse-machine/__tests__/__snapshots__/cse-machine-return-regressions.ts.snap
  src/cse-machine/__tests__/__snapshots__/cse-machine-stdlib.ts.snap
  src/cse-machine/__tests__/__snapshots__/cse-machine.ts.snap
  src/cse-machine/__tests__/cse-machine-errors.ts
  src/cse-machine/__tests__/cse-machine-return-regressions.ts
  src/cse-machine/__tests__/cse-machine-stdlib.ts
  src/cse-machine/__tests__/cse-machine.ts
  src/cse-machine/instrCreator.ts
  src/cse-machine/interpreter.ts
  src/cse-machine/types.ts
  src/cse-machine/utils.ts
  src/index.ts
  src/interpreter/closure.ts
  src/mocks/context.ts
  src/runner/sourceRunner.ts
  src/runner/utils.ts
  src/types.ts
Labels: Enhancement

#1521 CSE Machine: `hasXStatement` fixes
  src/cse-machine/__tests__/__snapshots__/cse-machine.ts.snap
  src/cse-machine/__tests__/cse-machine.ts
  src/cse-machine/utils.ts
Labels: Bug, important

#1527 CSE Machine: Fix display bug when scanning out declarations
  package.json
  src/cse-machine/interpreter.ts
  src/cse-machine/utils.ts
Labels: Bug

#1545 Nested break/continue statement detection fixes
  src/cse-machine/__tests__/__snapshots__/cse-machine.ts.snap
  src/cse-machine/__tests__/cse-machine.ts
  src/cse-machine/utils.ts
Labels: Bug

#1538 CSE Machine: Implement two-step block statement evaluation
  src/cse-machine/interpreter.ts
  src/cse-machine/utils.ts
  src/types.ts
Labels: Enhancement
