Repository source-academy/js-slang, pull requests merged in 2024-04, with the labels that each got.

#1642 CSE Machine: Overhaul environment handling at the start of programs
  src/cse-machine/interpreter.ts
Labels: Bug

#1653 1612 stepper accidental unpacking during evaluating the if statement in block expression
  src/stepper/__tests__/__snapshots__/stepper.ts.snap
  src/stepper/stepper.ts
Labels: Bug, minor

#1649 Amended stepper doc to new spec
  docs/specs/source_2_stepper_rules.tex
Labels: documentation

#1687 CSE Machine: Avoid pushing unnecessary env instructions
  src/cse-machine/__tests__/__snapshots__/cse-machine-runtime-context.ts.snap
  src/cse-machine/__tests__/cse-machine-runtime-context.ts
  src/cse-machine/interpreter.ts
  src/cse-machine/utils.ts
Labels: Enhancement

#1699 Temporary fix to speed up `canAvoidInstr`
  src/cse-machine/__tests__/__snapshots__/cse-machine-heap.ts.snap
  src/cse-machine/__tests__/__snapshots__/cse-machine-runtime-context.ts.snap
  src/cse-machine/__tests__/__snapshots__/cse-machine-unique-id.ts.snap
  src/cse-machine/interpreter.ts
  src/cse-machine/types.ts
  src/cse-machine/utils.ts
  src/types.ts
Labels: critical
