Repository source-academy/js-slang, pull requests merged in 2024-03, with the labels that each got.

#1577 Remove special cases for environment instruction generator
  src/cse-machine/interpreter.ts
Labels: Bug

#1597 1108 stepper programs that end with a declaration dont show correct result
  src/stepper/__tests__/__snapshots__/stepper.ts.snap
  src/stepper/__tests__/stepper.ts
  src/stepper/stepper.ts
Labels: Bug, minor

#1601 1588 accidental unpacking during evaluating the if statement
  src/stepper/stepper.ts
Labels: Bug, minor

#1606 CSE Machine: Implement navigation arrows to jump to the next/previous change in environment (js-slang)
  src/createContext.ts
  src/cse-machine/interpreter.ts
  src/cse-machine/utils.ts
  src/mocks/context.ts
  src/types.ts
Labels: Enhancement

#1600 CSE Machine: improve how objects are handled in environments, change id behavior
  src/__tests__/__snapshots__/environment.ts.snap
  src/__tests__/__snapshots__/environmentTree.ts.snap
  src/__tests__/environment.ts
  src/__tests__/environmentTree.ts
  src/__tests__/inspect.ts
  src/createContext.ts
  src/cse-machine/__tests__/__snapshots__/cse-machine-heap.ts.snap
  src/cse-machine/__tests__/__snapshots__/cse-machine-unique-id.ts.snap
  src/cse-machine/__tests__/cse-machine-heap.ts
  src/cse-machine/__tests__/cse-machine-unique-id.ts
  src/cse-machine/__tests__/cse-machine.ts
  src/cse-machine/heap.ts
  src/cse-machine/interpreter.ts
  src/cse-machine/types.ts
  src/cse-machine/utils.ts
  src/interpreter/closure.ts
  src/interpreter/interpreter-non-det.ts
  src/interpreter/interpreter.ts
  src/mocks/context.ts
  src/runner/sourceRunner.ts
  src/types.ts
Labels: Enhancement, Proposal

#1611 Add documentation for Source 4 Explicit-Control and Continuations
  docs/lib/continuation.js
  docs/md/README_4_EXPLICIT-CONTROL.md
  docs/md/README_CONTINUATION.md
  docs/md/README_top.md
  docs/specs/Makefile
  docs/specs/source_4_explicitcontrol.tex
  docs/specs/source_continuation.tex
  scripts/autocomplete.sh
  scripts/jsdoc.sh
  scripts/updateAutocompleteDocs.js
  src/createContext.ts
  src/cse-machine/__tests__/cse-machine-callcc-js.ts
  src/editors/ace/docTooltip/index.ts
Labels: Enhancement
